version: "3.0"

services:
  app:
    container_name: "app"
    volumes:
      - ./python_catch_up:/code/app
    build: .
    ports:
      - 8000:8000
    command: ["python", "main.py"]
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
